### PR TITLE
Contact form

### PR DESCRIPTION
**Pull request by chidiebereojingwa**
##  Contact form 
In this contact form we:
- Added name field
- Added textarea field
- Added mail field
- A submit button
- social icons

### CODE REVIEW

**Comment by alonsofl** [comment]
Hello, @chidiebereojingwa!
It seems that this PR has been already approved and merged. Would you explain this situation, please?
I would really appreciate it :raised_hands:

**Comment by chidiebereojingwa** [comment]
It was a pair programming assessment between me and my partner. where he
made changes on my code and I also made changes on his code as well

**Comment by alonsofl** [comment]
@chidiebereojingwa could you reach me on Slack, please?

**Comment by alonsofl** [comment]
Hi @chidiebereojingwa,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
